name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

          pip install -r src/requirements.txt

          pip install pytest pytest-cov flake8
      

      - name: Run flake8
        run: |
          cd src
          flake8 planner tests --max-line-length=100 --ignore=E203,W503


      - name: Run tests with coverage
        run: |
          cd src
          pytest tests --cov=planner --cov-report=term-missing --cov-report=xml


      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: src/coverage.xml
          fail_ci_if_error: false
